[env:m5stack-cores3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.21/platform-espressif32.zip
board = m5stack-cores3
framework = arduino
board_build.filesystem = littlefs
board_build.partitions = default_16MB.csv
build_unflags =
	-DARDUINO_USB_MODE=1
build_flags =
	-I src
	-DARDUINO_USB_MODE=0
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCORE_DEBUG_LEVEL=0
extra_scripts = pre:scripts/touch1200.py
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
lib_deps =
	m5stack/M5Unified
	m5stack/M5GFX
	bblanchon/ArduinoJson@^7
	https://github.com/m5stack/M5Faces.git
	h2zero/NimBLE-Arduino@^2.1
platform_packages =
	pioarduino/tool-esptoolpy @ https://github.com/pioarduino/esptool/releases/download/v5.0.2/esptool.zip
